// @flow
const RECEIVE_DYNAMIC_ATTRIBUTES: 'RECEIVE_DYNAMIC_ATTRIBUTES' = 'RECEIVE_DYNAMIC_ATTRIBUTES';
const RECORD_DYNAMIC_ATTRIBUTES_ERROR: 'RECORD_DYNAMIC_ATTRIBUTES_ERROR' = 'RECORD_DYNAMIC_ATTRIBUTES_ERROR';
const REQUEST_DYNAMIC_ATTRIBUTES: 'REQUEST_DYNAMIC_ATTRIBUTES' = 'REQUEST_DYNAMIC_ATTRIBUTES';
const SET_DYNAMIC_GROUPS: 'SET_DYNAMIC_GROUPS' = 'SET_DYNAMIC_GROUPS';
const UNKNOWN_DYNAMIC_GROUPS_ACTION: 'UNKNOWN_DYNAMIC_GROUPS_ACTION' = 'UNKNOWN_DYNAMIC_GROUPS_ACTION';

const DYNAMIC_GROUPS_EVENTS = {
	RECEIVE_DYNAMIC_ATTRIBUTES,
	RECORD_DYNAMIC_ATTRIBUTES_ERROR,
	REQUEST_DYNAMIC_ATTRIBUTES,
	SET_DYNAMIC_GROUPS,
	UNKNOWN_DYNAMIC_GROUPS_ACTION
};

export {
	DYNAMIC_GROUPS_EVENTS
};
