// @flow
export const ATTRIBUTE_EVENTS = {
	EMPTY_DATA: 'EMPTY_DATA',
	HIDE_LOADER_DATA: 'HIDE_LOADER_DATA',
	SET_ATTRIBUTE_DATA: 'SET_ATTRIBUTE_DATA',
	SET_ERROR_DATA: 'SET_ERROR_DATA',
	SHOW_LOADER_DATA: 'SHOW_LOADER_DATA'
};
