// @flow
const DAY: 'DAY' = 'DAY';
const WEEK: 'WEEK' = 'WEEK';
const MONTH: 'MONTH' = 'MONTH';
const QUARTER: 'QUARTER' = 'QUARTER';
const YEAR: 'YEAR' = 'YEAR';

const INTERVAL_MINUTE: 'INTERVAL_MINUTE' = 'INTERVAL_MINUTE';
const INTERVAL_HOUR: 'INTERVAL_HOUR' = 'INTERVAL_HOUR';
const INTERVAL_DAY: 'INTERVAL_DAY' = 'INTERVAL_DAY';
const INTERVAL_MONTH: 'INTERVAL_MONTH' = 'INTERVAL_MONTH';

const DATETIME: 'dateTime' = 'dateTime';
const DT_INTERVAL: 'dtInterval' = 'dtInterval';

const DATETIME_VARIANTS = {
	DAY,
	MONTH,
	QUARTER,
	WEEK,
	YEAR
};

const INTERVAL_VARIANTS = {
	INTERVAL_DAY,
	INTERVAL_HOUR,
	INTERVAL_MINUTE,
	INTERVAL_MONTH
};

const GROUP_TYPES = {
	DATETIME,
	DT_INTERVAL
};

const DATETIME_FORMAT = 'DD.MM.YYYY HH:mm';

export {
	DATETIME_FORMAT,
	DATETIME_VARIANTS,
	INTERVAL_VARIANTS,
	GROUP_TYPES
};
