// @flow
const HIDE_LOADER: 'HIDE_LOADER' = 'HIDE_LOADER';
const SET_COMMON_SETTINGS: 'SET_COMMON_SETTINGS' = 'SET_COMMON_SETTINGS';
const SET_CONTEXT: 'SET_CONTEXT' = 'SET_CONTEXT';
const SET_ERROR: 'SET_ERROR' = 'SET_ERROR';
const SET_RESOURCE_SETTINGS: 'SET_RESOURCE_SETTINGS' = 'SET_RESOURCE_SETTINGS';
const SET_SOURCES: 'SET_SOURCES' = 'SET_SOURCES';
const SHOW_LOADER: 'SHOW_LOADER' = 'SHOW_LOADER';
const UNKNOWN_APP_ACTION: 'UNKNOWN_APP_ACTION' = 'UNKNOWN_APP_ACTION';

const APP_EVENTS = {
	HIDE_LOADER,
	SET_COMMON_SETTINGS,
	SET_CONTEXT,
	SET_ERROR,
	SET_RESOURCE_SETTINGS,
	SET_SOURCES,
	SHOW_LOADER,
	UNKNOWN_APP_ACTION
};

// типы ролей пользователя
const MASTER: 'MASTER' = 'MASTER';
const REGULAR: 'REGULAR' = 'REGULAR';
const SUPER: 'SUPER' = 'SUPER';

const USER_ROLES = {
	MASTER,
	REGULAR,
	SUPER
};

export {APP_EVENTS, USER_ROLES};
