// @flow
const RECEIVE_LINK: 'RECEIVE_LINK' = 'RECEIVE_LINK';
const RECORD_LINK_ERROR: 'RECORD_LINK_ERROR' = 'RECORD_LINK_ERROR';
const REQUEST_LINK: 'REQUEST_LINK' = 'REQUEST_LINK';
const UNKNOWN_LINKS_ACTION: 'UNKNOWN_LINKS_ACTION' = 'UNKNOWN_LINKS_ACTION';

const LINKS_EVENTS = {
	RECEIVE_LINK,
	RECORD_LINK_ERROR,
	REQUEST_LINK,
	UNKNOWN_LINKS_ACTION
};

export {
	LINKS_EVENTS
};
