// @flow
const CHANGE_SEARCH_VALUE: 'CHANGE_SEARCH_VALUE' = 'CHANGE_SEARCH_VALUE';
const FOUND_OBJECTS_FULFILLED: 'FOUND_OBJECTS_FULFILLED' = 'FOUND_OBJECTS_FULFILLED';
const FOUND_OBJECTS_PENDING: 'FOUND_OBJECTS_PENDING' = 'FOUND_OBJECTS_PENDING';
const FOUND_OBJECT_REJECTED: 'FOUND_OBJECT_REJECTED' = 'FOUND_OBJECT_REJECTED';
const OBJECT_DATA_FULFILLED: 'OBJECT_DATA_FULFILLED' = 'OBJECT_DATA_FULFILLED';
const OBJECT_DATA_PENDING: 'OBJECT_DATA_PENDING' = 'OBJECT_DATA_PENDING';
const OBJECT_DATA_REJECTED: 'OBJECT_DATA_REJECTED' = 'OBJECT_DATA_REJECTED';
const UNKNOWN_OBJECTS_ACTION: 'UNKNOWN_OBJECTS_ACTION' = 'UNKNOWN_OBJECTS_ACTION';

const OBJECTS_EVENTS = {
	CHANGE_SEARCH_VALUE,
	FOUND_OBJECTS_FULFILLED,
	FOUND_OBJECTS_PENDING,
	FOUND_OBJECT_REJECTED,
	OBJECT_DATA_FULFILLED,
	OBJECT_DATA_PENDING,
	OBJECT_DATA_REJECTED,
	UNKNOWN_OBJECTS_ACTION
};

// Лимит значений возвращаемых запросом получения данных атрибута
const LIMIT = 20;

const ACTUAL: 'actual' = 'actual';
const ALL: 'all' = 'all';
const FOUND: 'found' = 'found';

const OBJECTS_DATA_TYPES = {
	ACTUAL,
	ALL,
	FOUND
};

export {
	OBJECTS_DATA_TYPES,
	OBJECTS_EVENTS,
	LIMIT
};
