// @flow
const RECEIVE_ACTUAL_OBJECT_DATA: 'RECEIVE_ACTUAL_OBJECT_DATA' = 'RECEIVE_ACTUAL_OBJECT_DATA';
const RECEIVE_ALL_OBJECT_DATA: 'RECEIVE_ALL_OBJECT_DATA' = 'RECEIVE_ALL_OBJECT_DATA';
const RECORD_ACTUAL_OBJECT_DATA_ERROR: 'RECORD_ACTUAL_OBJECT_DATA_ERROR' = 'RECORD_ACTUAL_OBJECT_DATA_ERROR';
const RECORD_ALL_OBJECT_DATA_ERROR: 'RECORD_ALL_OBJECT_DATA_ERROR' = 'RECORD_ALL_OBJECT_DATA_ERROR';
const REQUEST_ACTUAL_OBJECT_DATA: 'REQUEST_ACTUAL_OBJECT_DATA' = 'REQUEST_ACTUAL_OBJECT_DATA';
const REQUEST_ALL_OBJECT_DATA: 'REQUEST_ALL_OBJECT_DATA' = 'REQUEST_ALL_OBJECT_DATA';
const UNKNOWN_OBJECTS_ACTION: 'UNKNOWN_OBJECTS_ACTION' = 'UNKNOWN_OBJECTS_ACTION';

const OBJECTS_EVENTS = {
	RECEIVE_ACTUAL_OBJECT_DATA,
	RECEIVE_ALL_OBJECT_DATA,
	RECORD_ACTUAL_OBJECT_DATA_ERROR,
	RECORD_ALL_OBJECT_DATA_ERROR,
	REQUEST_ACTUAL_OBJECT_DATA,
	REQUEST_ALL_OBJECT_DATA,
	UNKNOWN_OBJECTS_ACTION
};

// Лимит значений возвращаемых запросом получения данных атрибута
const LIMIT = 20;

export {
	OBJECTS_EVENTS,
	LIMIT
};
