// @flow
const RECEIVE_REF_ATTRIBUTES: 'RECEIVE_REF_ATTRIBUTES' = 'RECEIVE_REF_ATTRIBUTES';
const RECORD_REF_ATTRIBUTES_ERROR: 'RECORD_REF_ATTRIBUTES_ERROR' = 'RECORD_REF_ATTRIBUTES_ERROR';
const REQUEST_REF_ATTRIBUTES: 'REQUEST_REF_ATTRIBUTES' = 'REQUEST_REF_ATTRIBUTES';
const UNKNOWN_REF_ATTRIBUTES_ACTION: 'UNKNOWN_REF_ATTRIBUTES_ACTION' = 'UNKNOWN_REF_ATTRIBUTES_ACTION';

const REF_ATTRIBUTES_EVENTS = {
	RECEIVE_REF_ATTRIBUTES,
	RECORD_REF_ATTRIBUTES_ERROR,
	REQUEST_REF_ATTRIBUTES,
	UNKNOWN_REF_ATTRIBUTES_ACTION
};

export {
	REF_ATTRIBUTES_EVENTS
};
