// @flow
export const SETTING_EVENTS = {
	EMPTY_DATA: 'EMPTY_DATA',
	HIDE_LOADER_DATA: 'HIDE_LOADER_DATA',
	SET_ERROR_DATA: 'SET_ERROR_DATA',
	SET_SETTING_DATA: 'SET_SETTING_DATA',
	SHOW_LOADER_DATA: 'SHOW_LOADER_DATA'
};
