// @flow
const SET_CALENDAR_LIST_LOADING: "SET_CALENDAR_LIST_LOADING"
	= 'SET_CALENDAR_LIST_LOADING';
const SET_CALENDAR_LIST: "SET_CALENDAR_LIST" = 'SET_CALENDAR_LIST';

const SET_ERROR: 'SET_ERROR' = 'SET_ERROR';

const SET_LOCATION_LIST_LOADING: "SET_LOCATION_LIST_LOADING"
	= 'SET_LOCATION_LIST_LOADING';
const SET_LOCATION_LIST: "SET_LOCATION_LIST" = 'SET_LOCATION_LIST';

const SET_SELECTED_OPTION: "SET_SELECTED_OPTION" = 'SET_SELECTED_OPTION';

const CALENDAR_SELECTORS_EVENTS = {
	SET_CALENDAR_LIST,
	SET_CALENDAR_LIST_LOADING,
	SET_ERROR,
	SET_LOCATION_LIST,
	SET_LOCATION_LIST_LOADING,
	SET_SELECTED_OPTION
};

export {
	CALENDAR_SELECTORS_EVENTS
};
