// @flow
const GET_LOCATION_LIST: "GET_LOCATION_LIST" = 'GET_LOCATION_LIST';
const SET_LOCATION_LIST_LOADING: "SET_LOCATION_LIST_LOADING"
	= 'SET_LOCATION_LIST_LOADING';
const SET_LOCATION_LIST: "SET_LOCATION_LIST" = 'SET_LOCATION_LIST';

const GET_CALENDAR_LIST: "GET_CALENDAR_LIST" = 'GET_CALENDAR_LIST';
const SET_CALENDAR_LIST_LOADING: "SET_CALENDAR_LIST_LOADING"
	= 'SET_CALENDAR_LIST_LOADING';
const SET_CALENDAR_LIST: "SET_CALENDAR_LIST" = 'SET_CALENDAR_LIST';

const SET_ERROR: 'SET_ERROR' = 'SET_ERROR';

const CALENDAR_SELECTORS_EVENTS = {
	GET_CALENDAR_LIST,
	GET_LOCATION_LIST,
	SET_CALENDAR_LIST,
	SET_CALENDAR_LIST_LOADING,
	SET_ERROR,
	SET_LOCATION_LIST,
	SET_LOCATION_LIST_LOADING
};

export {
	CALENDAR_SELECTORS_EVENTS
};
