// @flow
const SET_CALENDAR_DATA_LOADING: "SET_CALENDAR_DATA_LOADING"
	= 'SET_CALENDAR_DATA_LOADING';
const SET_CALENDAR_DATA: "SET_CALENDAR_DATA" = 'SET_CALENDAR_DATA';

const SET_CALENDAR_RESOURCE_COLOR_LIST: "SET_CALENDAR_RESOURCE_COLOR_LIST"
	= 'SET_CALENDAR_RESOURCE_COLOR_LIST';
const SET_CALENDAR_RESOURCE_COLOR_LIST_LOADING: "SET_CALENDAR_RESOURCE_COLOR_LIST_LOADING"
	= 'SET_CALENDAR_RESOURCE_COLOR_LIST_LOADING';

const SET_ERROR: "SET_ERROR" = 'SET_ERROR';

const CALENDAR_EVENTS = {
	SET_CALENDAR_DATA,
	SET_CALENDAR_DATA_LOADING,
	SET_CALENDAR_RESOURCE_COLOR_LIST,
	SET_CALENDAR_RESOURCE_COLOR_LIST_LOADING,
	SET_ERROR
};

export {CALENDAR_EVENTS};
