// @flow
export const VERIFY_EVENTS = {
	EMPTY_DATA: 'EMPTY_DATA',
	HIDE_LOADER_DATA: 'HIDE_LOADER_DATA',
	SET_ACTIVE_ELEMENT: 'SET_ACTIVE_ELEMENT',
	SET_DATA: 'SET_DATA',
	SET_ERROR_DATA: 'SET_ERROR_DATA',
	SET_EXPORT_TO: 'SET_EXPORT_TO',
	SET_NOTIFICATION_SHOW: 'SET_NOTIFICATION_SHOW',
	SET_POSITION: 'SET_POSITION',
	SET_SCALE: 'SET_SCALE',
	SHOW_LOADER_DATA: 'SHOW_LOADER_DATA'
};
