// @flow
export const VERIFY_EVENTS = {
	CHANGE_EDITING_GLOBAL: 'CHANGE_EDITING_GLOBAL',
	CHANGE_POPUP_SAVE_VIEWS: 'CHANGE_POPUP_SAVE_VIEWS',
	CHANGE_POPUP_SETTING_VIEWS: 'CHANGE_POPUP_SETTING_VIEWS',
	EMPTY_DATA: 'EMPTY_DATA',
	HIDE_LOADER_DATA: 'HIDE_LOADER_DATA',
	SET_ACTIVE_ELEMENT: 'SET_ACTIVE_ELEMENT',
	SET_CENTER_POINT_UUID: 'SET_CENTER_POINT_UUID',
	SET_DEFAULT_LOCATION_POINTS: 'SET_DEFAULT_LOCATION_POINTS',
	SET_DEFAULT_VIEW_DATA: 'SET_DEFAULT_VIEW_DATA',
	SET_EDIT_FORM: 'SET_EDIT_FORM',
	SET_ENTITIES_DATA: 'SET_ENTITIES_DATA',
	SET_ERROR_DATA: 'SET_ERROR_DATA',
	SET_EXPORT_TO: 'SET_EXPORT_TO',
	SET_LIST_VIEWS: 'SET_LIST_VIEWS',
	SET_NOTIFICATION_SHOW: 'SET_NOTIFICATION_SHOW',
	SET_POSITION: 'SET_POSITION',
	SET_SCALE: 'SET_SCALE',
	SET_SEARCH_POINTS: 'SET_SEARCH_POINTS',
	SET_SEARCH_TEXT: 'SET_SEARCH_TEXT',
	SHOW_LOADER_DATA: 'SHOW_LOADER_DATA'
};
