// @flow
import Api from './api';
import FakeApi from './fakeApi';
import {
	addNewWork,
	applyVersion,
	checkWorksOfResource,
	createPersonalViewDiagram,
	deletePersonalViewDiagram,
	deleteWorkDateRanges,
	deleteGanttVersionSettingsRequest,
	editWorkData,
	editWorkDateRangesFromVersionRequest,
	getAttributeGroups,
	getContext,
	getCurrentUser,
	getDataAttributesControlPointStatus,
	getDataSourceAttributes,
	getDataSourceAttributesByTypes,
	getDataSources,
	getDiagramData,
	getGanttVersionsSettings,
	getGanttVersionTitlesAndKeys,
	getInitialParams,
	getInitialSettings,
	getUserData,
	getUsers,
	getWorks,
	getWorkAttributes,
	getWorkDataForWork,
	openFilterForm,
	postChangedWorkInterval,
	postChangedWorkProgress,
	postChangedWorkRelations,
	postUsers,
	saveData,
	saveGanttColorSettings,
	saveGanttVersionSettingsRequest
} from './context';

export {
	addNewWork,
	applyVersion,
	checkWorksOfResource,
	createPersonalViewDiagram,
	deletePersonalViewDiagram,
	deleteWorkDateRanges,
	deleteGanttVersionSettingsRequest,
	editWorkData,
	editWorkDateRangesFromVersionRequest,
	getAttributeGroups,
	getContext,
	getCurrentUser,
	getDataAttributesControlPointStatus,
	getDataSourceAttributes,
	getDataSourceAttributesByTypes,
	getDataSources,
	getDiagramData,
	getGanttVersionsSettings,
	getGanttVersionTitlesAndKeys,
	getInitialParams,
	getInitialSettings,
	getUserData,
	getUsers,
	getWorks,
	getWorkAttributes,
	getWorkDataForWork,
	openFilterForm,
	postChangedWorkInterval,
	postChangedWorkProgress,
	postChangedWorkRelations,
	postUsers,
	saveData,
	saveGanttColorSettings,
	saveGanttVersionSettingsRequest
};

export const api = process.env.NODE_ENV === 'development' ? new FakeApi() : new Api();