// @flow
const RECEIVE_META_CLASS_STATES: 'RECEIVE_META_CLASS_STATES' = 'RECEIVE_META_CLASS_STATES';
const RECORD_META_CLASS_STATES_ERROR: 'RECORD_META_CLASS_STATES_ERROR' = 'RECORD_META_CLASS_STATES_ERROR';
const REQUEST_META_CLASS_STATES: 'REQUEST_META_CLASS_STATES' = 'REQUEST_META_CLASS_STATES';
const UNKNOWN_STATES_ACTION: 'UNKNOWN_STATES_ACTION' = 'UNKNOWN_STATES_ACTION';

const STATES_EVENTS = {
	RECEIVE_META_CLASS_STATES,
	RECORD_META_CLASS_STATES_ERROR,
	REQUEST_META_CLASS_STATES,
	UNKNOWN_STATES_ACTION
};

export {
	STATES_EVENTS
};
