// @flow
const SET_APP_LOADING: "SET_APP_LOADING"
	= 'SET_APP_LOADING';
const SET_APP_INIT_DATA: "SET_APP_INIT_DATA" = 'SET_APP_INIT_DATA';

const SET_ERROR: "SET_ERROR" = 'SET_ERROR';

const APP_EVENTS = {
	SET_APP_INIT_DATA,
	SET_APP_LOADING,
	SET_ERROR
};

export {APP_EVENTS};
