// @flow
const RECEIVE_META_CLASS_DATA: 'RECEIVE_META_CLASS_DATA' = 'RECEIVE_META_CLASS_DATA';
const RECORD_META_CLASS_DATA_ERROR: 'RECORD_META_CLASS_DATA_ERROR' = 'RECORD_META_CLASS_DATA_ERROR';
const REQUEST_META_CLASS_DATA: 'REQUEST_META_CLASS_DATA' = 'REQUEST_META_CLASS_DATA';
const UNKNOWN_META_CLASSES_ACTION: 'UNKNOWN_META_CLASSES_ACTION' = 'UNKNOWN_META_CLASSES_ACTION';

const META_CLASSES_EVENTS = {
	RECEIVE_META_CLASS_DATA,
	RECORD_META_CLASS_DATA_ERROR,
	REQUEST_META_CLASS_DATA,
	UNKNOWN_META_CLASSES_ACTION
};

export {
	META_CLASSES_EVENTS
};
