// @flow
import {DEFAULT_AGGREGATION, INTEGER_AGGREGATION} from 'store/widgets/constants';

const COUNT_APPLICABLE_OPTION = {
	label: 'CNT',
	value: DEFAULT_AGGREGATION.COUNT
};

const PERCENT_APPLICABLE_OPTION = {
	label: '%',
	value: DEFAULT_AGGREGATION.PERCENT
};

const PERCENT_COUNT_APPLICABLE_OPTION = {
	label: 'CNT(%)',
	value: DEFAULT_AGGREGATION.PERCENT_CNT
};

const SUM_APPLICABLE_OPTION = {
	label: 'SUM',
	value: INTEGER_AGGREGATION.SUM
};

const MAX_APPLICABLE_OPTION = {
	label: 'MAX',
	value: INTEGER_AGGREGATION.MAX
};

const MIN_APPLICABLE_OPTION = {
	label: 'MIN',
	value: INTEGER_AGGREGATION.MIN
};

const NOT_APPLICABLE_OPTION = {
	label: 'N/A',
	value: DEFAULT_AGGREGATION.NOT_APPLICABLE
};

const AVG_APPLICABLE_OPTION = {
	label: 'AVG',
	value: INTEGER_AGGREGATION.AVG
};

const DEFAULT_AGGREGATION_OPTIONS = [
	COUNT_APPLICABLE_OPTION,
	PERCENT_APPLICABLE_OPTION,
	PERCENT_COUNT_APPLICABLE_OPTION
];

const INTEGER_AGGREGATION_OPTIONS = [
	SUM_APPLICABLE_OPTION,
	MAX_APPLICABLE_OPTION,
	MIN_APPLICABLE_OPTION
];

export {
	AVG_APPLICABLE_OPTION,
	COUNT_APPLICABLE_OPTION,
	DEFAULT_AGGREGATION_OPTIONS,
	INTEGER_AGGREGATION_OPTIONS,
	MAX_APPLICABLE_OPTION,
	MIN_APPLICABLE_OPTION,
	NOT_APPLICABLE_OPTION,
	PERCENT_APPLICABLE_OPTION,
	SUM_APPLICABLE_OPTION
};
