// @flow
import {DEFAULT_AGGREGATION, INTEGER_AGGREGATION} from 'store/widgets/constants';

const NOT_APPLICABLE_OPTION = {
	label: 'N/A',
	value: DEFAULT_AGGREGATION.NOT_APPLICABLE
};

const AVG_APPLICABLE_OPTION = {
	label: 'AVG',
	value: INTEGER_AGGREGATION.AVG
};

const DEFAULT_AGGREGATION_OPTIONS = [
	{
		label: 'CNT',
		value: DEFAULT_AGGREGATION.COUNT
	},
	{
		label: '%',
		value: DEFAULT_AGGREGATION.PERCENT
	}
];

const INTEGER_AGGREGATION_OPTIONS = [
	{
		label: 'SUM',
		value: INTEGER_AGGREGATION.SUM
	},
	{
		label: 'MAX',
		value: INTEGER_AGGREGATION.MAX
	},
	{
		label: 'MIN',
		value: INTEGER_AGGREGATION.MIN
	}
];

export {
	AVG_APPLICABLE_OPTION,
	DEFAULT_AGGREGATION_OPTIONS,
	INTEGER_AGGREGATION_OPTIONS,
	NOT_APPLICABLE_OPTION
};
