// @flow
export const USER_EVENTS = {
	EMPTY_DATA: 'EMPTY_DATA',
	HIDE_LOADER_DATA: 'HIDE_LOADER_DATA',
	SET_ERROR_DATA: 'SET_ERROR_DATA',
	SET_USER_DATA: 'SET_USER_DATA',
	SHOW_LOADER_DATA: 'SHOW_LOADER_DATA'
};
