// @flow
export const VERIFICATION_EVENTS = {
	EMPTY_DATA: 'EMPTY_DATA',
	HIDE_LOADER_DATA: 'HIDE_LOADER_DATA',
	SET_ERROR_DATA: 'SET_ERROR_DATA',
	SET_STEP_VERIFICATION: 'SET_STEP_VERIFICATION',
	SET_VERIFICATION_ATTRIBUTE: 'SET_VERIFICATION_ATTRIBUTE',
	SET_VERIFICATION_RESULT: 'SET_VERIFICATION_RESULT',
	SHOW_LOADER_DATA: 'SHOW_LOADER_DATA'
};
