// @flow
const ADD_WIDGET: 'ADD_WIDGET' = 'ADD_WIDGET';
const CLOSE_WIDGET_PANEL: 'CLOSE_WIDGET_PANEL' = 'CLOSE_WIDGET_PANEL';
const EDIT_WIDGET: 'EDIT_WIDGET' = 'EDIT_WIDGET';
const EDIT_LAYOUT: 'EDIT_LAYOUT' = 'EDIT_LAYOUT';
const UPDATE_WIDGET: 'UPDATE_WIDGET' = 'UPDATE_WIDGET';

const DASHBOARD_EVENTS = {
	ADD_WIDGET,
	CLOSE_WIDGET_PANEL,
	EDIT_LAYOUT,
	EDIT_WIDGET,
	UPDATE_WIDGET
};

export {DASHBOARD_EVENTS};
