// @flow
const CHANGE_AUTO_UPDATE_SETTINGS: 'CHANGE_AUTO_UPDATE_SETTINGS' = 'CHANGE_AUTO_UPDATE_SETTINGS';
const RECEIVE_DASHBOARD: 'RECEIVE_DASHBOARD' = 'RECEIVE_DASHBOARD';
const RECEIVE_USER_ROLE: 'RECEIVE_USER_ROLE' = 'RECEIVE_USER_ROLE';
const RECORD_DASHBOARD_ERROR: 'RECORD_DASHBOARD_ERROR' = 'RECORD_DASHBOARD_ERROR';
const REQUEST_DASHBOARD: 'REQUEST_DASHBOARD' = 'REQUEST_DASHBOARD';
const SET_AUTO_UPDATE_FUNCTION: 'SET_AUTO_UPDATE_FUNCTION' = 'SET_AUTO_UPDATE_FUNCTION';
const SET_CONTEXT: 'SET_CONTEXT' = 'SET_CONTEXT';
const SET_EDITABLE_PARAM: 'SET_EDITABLE_PARAM' = 'SET_EDITABLE_PARAM';
const SWITCH_ON_EDIT_MODE: 'SWITCH_ON_EDIT_MODE' = 'SWITCH_ON_EDIT_MODE';
const SWITCH_OFF_EDIT_MODE: 'SWITCH_OFF_EDIT_MODE' = 'SWITCH_OFF_EDIT_MODE';
const UNKNOWN_DASHBOARD_ACTION: 'UNKNOWN_DASHBOARD_ACTION' = 'UNKNOWN_DASHBOARD_ACTION';

const DASHBOARD_EVENTS = {
	CHANGE_AUTO_UPDATE_SETTINGS,
	RECEIVE_DASHBOARD,
	RECEIVE_USER_ROLE,
	RECORD_DASHBOARD_ERROR,
	REQUEST_DASHBOARD,
	SET_AUTO_UPDATE_FUNCTION,
	SET_CONTEXT,
	SET_EDITABLE_PARAM,
	SWITCH_ON_EDIT_MODE,
	SWITCH_OFF_EDIT_MODE,
	UNKNOWN_DASHBOARD_ACTION
};

export {DASHBOARD_EVENTS};
