// @flow
const CHANGE_AUTO_UPDATE_SETTINGS: 'CHANGE_AUTO_UPDATE_SETTINGS' = 'CHANGE_AUTO_UPDATE_SETTINGS';
const CREATE_PERSONAL_DASHBOARD: 'CREATE_PERSONAL_DASHBOARD' = 'CREATE_PERSONAL_DASHBOARD';
const CREATED_PERSONAL_DASHBOARD: 'CREATED_PERSONAL_DASHBOARD' = 'CREATED_PERSONAL_DASHBOARD';
const DELETE_PERSONAL_DASHBOARD: 'DELETE_PERSONAL_DASHBOARD' = 'DELETE_PERSONAL_DASHBOARD';
const DELETED_PERSONAL_DASHBOARD: 'DELETED_PERSONAL_DASHBOARD' = 'DELETED_PERSONAL_DASHBOARD';
const ERROR_CREATE_PERSONAL_DASHBOARD: 'CREATE_PERSONAL_DASHBOARD' = 'CREATE_PERSONAL_DASHBOARD';
const ERROR_DELETE_PERSONAL_DASHBOARD: 'ERROR_DELETE_PERSONAL_DASHBOARD' = 'ERROR_DELETE_PERSONAL_DASHBOARD';
const RECEIVE_DASHBOARD: 'RECEIVE_DASHBOARD' = 'RECEIVE_DASHBOARD';
const RECORD_DASHBOARD_ERROR: 'RECORD_DASHBOARD_ERROR' = 'RECORD_DASHBOARD_ERROR';
const REQUEST_DASHBOARD: 'REQUEST_DASHBOARD' = 'REQUEST_DASHBOARD';
const SET_EDITABLE_PARAM: 'SET_EDITABLE_PARAM' = 'SET_EDITABLE_PARAM';
const SET_PERSONAL: 'SET_PERSONAL' = 'SET_PERSONAL';
const SWITCH_OFF_EDIT_MODE: 'SWITCH_OFF_EDIT_MODE' = 'SWITCH_OFF_EDIT_MODE';
const SWITCH_ON_EDIT_MODE: 'SWITCH_ON_EDIT_MODE' = 'SWITCH_ON_EDIT_MODE';
const UNKNOWN_DASHBOARD_ACTION: 'UNKNOWN_DASHBOARD_ACTION' = 'UNKNOWN_DASHBOARD_ACTION';

const DASHBOARD_EVENTS = {
	CHANGE_AUTO_UPDATE_SETTINGS,
	CREATED_PERSONAL_DASHBOARD,
	CREATE_PERSONAL_DASHBOARD,
	DELETED_PERSONAL_DASHBOARD,
	DELETE_PERSONAL_DASHBOARD,
	ERROR_CREATE_PERSONAL_DASHBOARD,
	ERROR_DELETE_PERSONAL_DASHBOARD,
	RECEIVE_DASHBOARD,
	RECORD_DASHBOARD_ERROR,
	REQUEST_DASHBOARD,
	SET_EDITABLE_PARAM,
	SET_PERSONAL,
	SWITCH_OFF_EDIT_MODE,
	SWITCH_ON_EDIT_MODE,
	UNKNOWN_DASHBOARD_ACTION
};

const DEFAULT_INTERVAL = 15;

export {
	DASHBOARD_EVENTS,
	DEFAULT_INTERVAL
};
