// @flow
const SET_CONTEXT: 'SET_CONTEXT' = 'SET_CONTEXT';
const SET_PARAMS: 'SET_PARAMS' = 'SET_PARAMS';
const SET_DATA_GEOLOCATION: 'SET_DATA_GEOLOCATION' = 'SET_DATA_GEOLOCATION';
const RELOAD_ACTIVE_POINT: 'RELOAD_GEOLOCATION_POINT' = 'RELOAD_GEOLOCATION_POINT';
const RECORD_GEOLOCATION_ERROR: 'RECORD_GEOLOCATION_ERROR' = 'RECORD_GEOLOCATION_ERROR';
const RESET_SINGLE_POINT: 'RESET_SINGLE_POINT' = 'RESET_SINGLE_POINT';
const UNKNOWN_GEOLOCATION_ACTION: 'UNKNOWN_GEOLOCATION_ACTION' = 'UNKNOWN_GEOLOCATION_ACTION';
const TOGGLE_FILTER: 'TOGGLE_FILTER' = 'TOGGLE_FILTER';
const TOGGLE_PANEL: 'TOGGLE_PANEL' = 'TOGGLE_PANEL';
const SET_TAB: 'SET_TAB' = 'SET_TAB';
const SET_SINGLE_POINT: 'SET_SINGLE_POINT' = 'SET_SINGLE_POINT';
const TOGGLE_GROUP: 'TOGGLE_GROUP' = 'TOGGLE_GROUP';
const SELECT_ALL_GROUPS: 'SELECT_ALL_GROUPS' = 'SELECT_ALL_GROUPS';
const RESET_ALL_GROUPS: 'RESET_ALL_GROUPS' = 'RESET_ALL_GROUPS';
const CHANGE_ZOOM: 'CHANGE_ZOOM' = 'CHANGE_ZOOM';
const TOGGLE_MAP_PANEL: 'TOGGLE_MAP_PANEL' = 'TOGGLE_MAP_PANEL';
const TOGGLE_MAP_CONTENT_MENU: 'TOGGLE_MAP_CONTENT_MENU' = 'TOGGLE_MAP_CONTENT_MENU';
const SET_MAP_PANEL: 'SET_MAP_PANEL' = 'SET_MAP_PANEL';

const GEOLOCATION_EVENTS = {
	CHANGE_ZOOM,
	RECORD_GEOLOCATION_ERROR,
	RELOAD_ACTIVE_POINT,
	RESET_ALL_GROUPS,
	RESET_SINGLE_POINT,
	SELECT_ALL_GROUPS,
	SET_CONTEXT,
	SET_DATA_GEOLOCATION,
	SET_MAP_PANEL,
	SET_PARAMS,
	SET_SINGLE_POINT,
	SET_TAB,
	TOGGLE_FILTER,
	TOGGLE_GROUP,
	TOGGLE_MAP_CONTENT_MENU,
	TOGGLE_MAP_PANEL,
	TOGGLE_PANEL,
	UNKNOWN_GEOLOCATION_ACTION
};

export {GEOLOCATION_EVENTS};
