// @flow
const LARGE: 'LARGE' = 'LARGE';
const NORMAL: 'NORMAL' = 'NORMAL';
const SMALL: 'SMALL' = 'SMALL';

const SIZES = {
	LARGE,
	NORMAL,
	SMALL
};

const LEFT: 'LEFT' = 'LEFT';
const RIGHT: 'RIGHT' = 'RIGHT';

const FOOTER_POSITIONS = {
	LEFT,
	RIGHT
};

const SUBMIT_BUTTON: 'SUBMIT_BUTTON' = 'SUBMIT_BUTTON';
const CANCEL_BUTTON: 'CANCEL_BUTTON' = 'CANCEL_BUTTON';

const DEFAULT_BUTTONS = {
	CANCEL_BUTTON,
	SUBMIT_BUTTON
};

export {
	DEFAULT_BUTTONS,
	FOOTER_POSITIONS,
	SIZES
};
