// @flow
const REMOVE_CUSTOM_GROUP: 'REMOVE_CUSTOM_GROUP' = 'REMOVE_CUSTOM_GROUP';
const SAVE_CUSTOM_GROUP: 'SAVE_CUSTOM_GROUP' = 'SAVE_CUSTOM_GROUP';
const SET_CUSTOM_GROUPS: 'SET_CUSTOM_GROUPS' = 'SET_CUSTOM_GROUPS';
const UNKNOWN_CUSTOM_GROUPS_ACTION: 'UNKNOWN_CUSTOM_GROUPS_ACTION' = 'UNKNOWN_CUSTOM_GROUPS_ACTION';

const CUSTOM_GROUPS_EVENTS = {
	REMOVE_CUSTOM_GROUP,
	SAVE_CUSTOM_GROUP,
	SET_CUSTOM_GROUPS,
	UNKNOWN_CUSTOM_GROUPS_ACTION
};

// Типы данных операндов условий подгрупп
// DATETIME
const BETWEEN: 'BETWEEN' = 'BETWEEN';
const LAST: 'LAST' = 'LAST';
const NEAR: 'NEAR' = 'NEAR';
const TODAY: 'TODAY' = 'TODAY';

// INTEGER
const EMPTY: 'EMPTY' = 'EMPTY';
const EQUAL: 'EQUAL' = 'EQUAL';
const GREATER: 'GREATER' = 'GREATER';
const LESS: 'LESS' = 'LESS';
const NOT_EMPTY: 'NOT_EMPTY' = 'NOT_EMPTY';
const NOT_EQUAL: 'NOT_EQUAL' = 'NOT_EQUAL';
const NOT_EQUAL_NOT_EMPTY: 'NOT_EQUAL_NOT_EMPTY' = 'NOT_EQUAL_NOT_EMPTY';

// REF
const CONTAINS: 'CONTAINS' = 'CONTAINS';
const CONTAINS_ANY: 'CONTAINS_ANY' = 'CONTAINS_ANY';
const CONTAINS_ATTR_CURRENT_OBJECT: 'CONTAINS_ATTR_CURRENT_OBJECT' = 'CONTAINS_ATTR_CURRENT_OBJECT';
const CONTAINS_CURRENT_OBJECT: 'CONTAINS_CURRENT_OBJECT' = 'CONTAINS_CURRENT_OBJECT';
const CONTAINS_INCLUDING_ARCHIVAL: 'CONTAINS_INCLUDING_ARCHIVAL' = 'CONTAINS_INCLUDING_ARCHIVAL';
const CONTAINS_INCLUDING_NESTED: 'CONTAINS_INCLUDING_NESTED' = 'CONTAINS_INCLUDING_NESTED';
const EQUAL_CURRENT_OBJECT: 'EQUAL_CURRENT_OBJECT' = 'EQUAL_CURRENT_OBJECT';
const EQUAL_ATTR_CURRENT_OBJECT: 'EQUAL_ATTR_CURRENT_OBJECT' = 'EQUAL_ATTR_CURRENT_OBJECT';
const EXPIRATION_CONTAINS: 'EXPIRATION_CONTAINS' = 'EXPIRATION_CONTAINS';
const EXPIRES_BETWEEN: 'EXPIRES_BETWEEN' = 'EXPIRES_BETWEEN';
const NOT_CONTAINS: 'NOT_CONTAINS' = 'NOT_CONTAINS';
const NOT_CONTAINS_INCLUDING_ARCHIVAL: 'NOT_CONTAINS_INCLUDING_ARCHIVAL' = 'NOT_CONTAINS_INCLUDING_ARCHIVAL';
const TITLE_CONTAINS: 'TITLE_CONTAINS' = 'TITLE_CONTAINS';
const TITLE_NOT_CONTAINS: 'TITLE_NOT_CONTAINS' = 'TITLE_NOT_CONTAINS';
const STATUS_CONTAINS: 'STATUS_CONTAINS' = 'STATUS_CONTAINS';
const STATUS_NOT_CONTAINS: 'STATUS_NOT_CONTAINS' = 'STATUS_NOT_CONTAINS';

// STRING
const NOT_CONTAINS_INCLUDING_EMPTY: 'NOT_CONTAINS_INCLUDING_EMPTY' = 'NOT_CONTAINS_INCLUDING_EMPTY';

const OPERAND_TYPES = {
	BETWEEN,
	CONTAINS,
	CONTAINS_ANY,
	CONTAINS_ATTR_CURRENT_OBJECT,
	CONTAINS_CURRENT_OBJECT,
	CONTAINS_INCLUDING_ARCHIVAL,
	CONTAINS_INCLUDING_NESTED,
	EMPTY,
	EQUAL,
	EQUAL_ATTR_CURRENT_OBJECT,
	EQUAL_CURRENT_OBJECT,
	EXPIRATION_CONTAINS,
	EXPIRES_BETWEEN,
	GREATER,
	LAST,
	LESS,
	NEAR,
	NOT_CONTAINS,
	NOT_CONTAINS_INCLUDING_ARCHIVAL,
	NOT_CONTAINS_INCLUDING_EMPTY,
	NOT_EMPTY,
	NOT_EQUAL,
	NOT_EQUAL_NOT_EMPTY,
	STATUS_CONTAINS,
	STATUS_NOT_CONTAINS,
	TITLE_CONTAINS,
	TITLE_NOT_CONTAINS,
	TODAY
};

const SIMPLE_DATE = {
	LAST,
	NEAR
};

const NUMBER = {
	EQUAL,
	GREATER,
	LESS,
	NOT_EQUAL,
	NOT_EQUAL_NOT_EMPTY
};

const INTERVAL = {
	EQUAL,
	GREATER,
	LESS,
	NOT_EQUAL
};

const REF = {
	CONTAINS,
	CONTAINS_ATTR_CURRENT_OBJECT,
	CONTAINS_CURRENT_OBJECT,
	CONTAINS_INCLUDING_ARCHIVAL,
	CONTAINS_INCLUDING_NESTED,
	EQUAL_ATTR_CURRENT_OBJECT,
	NOT_CONTAINS,
	NOT_CONTAINS_INCLUDING_ARCHIVAL
};

const SIMPLE_REF = {
	TITLE_CONTAINS,
	TITLE_NOT_CONTAINS
};

const STRING = {
	CONTAINS,
	NOT_CONTAINS,
	NOT_CONTAINS_INCLUDING_EMPTY
};

const OPERAND_SETS = {
	INTERVAL,
	NUMBER,
	REF,
	SIMPLE_DATE,
	SIMPLE_REF,
	STRING
};

export {
	CUSTOM_GROUPS_EVENTS,
	OPERAND_SETS,
	OPERAND_TYPES
};
