// @flow
const REMOVE_CUSTOM_GROUP: 'REMOVE_CUSTOM_GROUP' = 'REMOVE_CUSTOM_GROUP';
const SAVE_CUSTOM_GROUP: 'SAVE_CUSTOM_GROUP' = 'SAVE_CUSTOM_GROUP';
const SET_CUSTOM_GROUPS: 'SET_CUSTOM_GROUPS' = 'SET_CUSTOM_GROUPS';
const UNKNOWN_CUSTOM_GROUPS_ACTION: 'UNKNOWN_CUSTOM_GROUPS_ACTION' = 'UNKNOWN_CUSTOM_GROUPS_ACTION';

const CUSTOM_GROUPS_EVENTS = {
	REMOVE_CUSTOM_GROUP,
	SAVE_CUSTOM_GROUP,
	SET_CUSTOM_GROUPS,
	UNKNOWN_CUSTOM_GROUPS_ACTION
};

// Типы данных операндов условий подгрупп
// DATETIME
const BETWEEN: 'BETWEEN' = 'BETWEEN';
const LAST: 'LAST' = 'LAST';
const NEAR: 'NEAR' = 'NEAR';
const TODAY: 'TODAY' = 'TODAY';

// INTEGER
const EMPTY: 'EMPTY' = 'EMPTY';
const EQUAL: 'EQUAL' = 'EQUAL';
const GREATER: 'GREATER' = 'GREATER';
const LESS: 'LESS' = 'LESS';
const NOT_EMPTY: 'NOT_EMPTY' = 'NOT_EMPTY';
const NOT_EQUAL: 'NOT_EQUAL' = 'NOT_EQUAL';
const NOT_EQUAL_NOT_EMPTY: 'NOT_EQUAL_NOT_EMPTY' = 'NOT_EQUAL_NOT_EMPTY';

const CONDITION_TYPES = {
	BETWEEN,
	EMPTY,
	EQUAL,
	GREATER,
	LAST,
	LESS,
	NEAR,
	NOT_EMPTY,
	NOT_EQUAL,
	NOT_EQUAL_NOT_EMPTY,
	TODAY
};

export {
	CONDITION_TYPES,
	CUSTOM_GROUPS_EVENTS
};
