// @flow
const RECEIVE_LINKED_DATA_SOURCES: 'RECEIVE_LINKED_DATA_SOURCES' = 'RECEIVE_LINKED_DATA_SOURCES';
const RECORD_LINKED_DATA_SOURCES_ERROR: 'RECORD_LINKED_DATA_SOURCES_ERROR' = 'RECORD_LINKED_DATA_SOURCES_ERROR';
const REQUEST_LINKED_DATA_SOURCES: 'REQUEST_LINKED_DATA_SOURCES' = 'REQUEST_LINKED_DATA_SOURCES';
const UNKNOWN_LINKED_DATA_SOURCES_ACTION: 'UNKNOWN_LINKED_DATA_SOURCES_ACTION' = 'UNKNOWN_LINKED_DATA_SOURCES_ACTION';

const LINKED_DATA_SOURCES_EVENTS = {
	RECEIVE_LINKED_DATA_SOURCES,
	RECORD_LINKED_DATA_SOURCES_ERROR,
	REQUEST_LINKED_DATA_SOURCES,
	UNKNOWN_LINKED_DATA_SOURCES_ACTION
};

export {
	LINKED_DATA_SOURCES_EVENTS
};
