// @flow
const BREAKDOWN: 'BREAKDOWN' = 'BREAKDOWN';
const INDICATOR: 'INDICATOR' = 'INDICATOR';
const PARAMETER: 'PARAMETER' = 'PARAMETER';

const COLUMN_TYPES = {
	BREAKDOWN,
	INDICATOR,
	PARAMETER
};

const ID_ACCESSOR: 'ID' = 'ID';

export {
	COLUMN_TYPES,
	ID_ACCESSOR
};
