// @flow
const RECORD_DASHBOARDS_ERROR: 'RECORD_DASHBOARDS_ERROR' = 'RECORD_DASHBOARDS_ERROR';
const REQUEST_DASHBOARDS: 'REQUEST_DASHBOARDS' = 'REQUEST_DASHBOARDS';
const RESPONSE_DASHBOARDS: 'RESPONSE_DASHBOARDS' = 'RESPONSE_DASHBOARDS';
const UNKNOWN_DASHBOARDS_ACTION: 'UNKNOWN_DASHBOARDS_ACTION' = 'UNKNOWN_DASHBOARDS_ACTION';

const DASHBOARDS_EVENTS = {
	RECORD_DASHBOARDS_ERROR,
	REQUEST_DASHBOARDS,
	RESPONSE_DASHBOARDS,
	UNKNOWN_DASHBOARDS_ACTION
};

export {
	DASHBOARDS_EVENTS
};
