// @flow
const RECEIVE_DIAGRAM: 'RECEIVE_DIAGRAM' = 'RECEIVE_DIAGRAM';
const RECORD_DIAGRAM_ERROR: 'RECORD_DIAGRAM_ERROR' = 'RECORD_DIAGRAM_ERROR';
const REQUEST_DIAGRAM: 'REQUEST_DIAGRAM' = 'REQUEST_DIAGRAM';
const UNKNOWN_DIAGRAMS_ACTION: 'UNKNOWN_DIAGRAMS_ACTION' = 'UNKNOWN_DIAGRAMS_ACTION';

const DIAGRAMS_EVENTS = {
	RECEIVE_DIAGRAM,
	RECORD_DIAGRAM_ERROR,
	REQUEST_DIAGRAM,
	UNKNOWN_DIAGRAMS_ACTION
};

export {
	DIAGRAMS_EVENTS
};
