// @flow
const RECEIVE_DIAGRAM: 'RECEIVE_DIAGRAM' = 'RECEIVE_DIAGRAM';
const RECEIVE_DIAGRAMS: 'RECEIVE_DIAGRAMS' = 'RECEIVE_DIAGRAMS';
const RECORD_DIAGRAM_ERROR: 'RECORD_DIAGRAM_ERROR' = 'RECORD_DIAGRAM_ERROR';
const RECORD_DIAGRAMS_ERROR: 'RECORD_DIAGRAMS_ERROR' = 'RECORD_DIAGRAMS_ERROR';
const REQUEST_DIAGRAM: 'REQUEST_DIAGRAM' = 'REQUEST_DIAGRAM';
const REQUEST_DIAGRAMS: 'REQUEST_DIAGRAMS' = 'REQUEST_DIAGRAMS';
const UNKNOWN_DIAGRAMS_ACTION: 'UNKNOWN_DIAGRAMS_ACTION' = 'UNKNOWN_DIAGRAMS_ACTION';

const DIAGRAMS_EVENTS = {
	RECEIVE_DIAGRAM,
	RECEIVE_DIAGRAMS,
	RECORD_DIAGRAM_ERROR,
	RECORD_DIAGRAMS_ERROR,
	REQUEST_DIAGRAM,
	REQUEST_DIAGRAMS,
	UNKNOWN_DIAGRAMS_ACTION
};

export {
	DIAGRAMS_EVENTS
};
