// @flow
const RECEIVE_CHART: 'RECEIVE_CHART' = 'RECEIVE_CHART';
const RECORD_CHART_ERROR: 'RECORD_CHART_ERROR' = 'RECORD_CHART_ERROR';
const REQUEST_CHART: 'REQUEST_CHART' = 'REQUEST_CHART';
const UNKNOWN_CHARTS_ACTION: 'UNKNOWN_CHARTS_ACTION' = 'UNKNOWN_CHARTS_ACTION';

const CHARTS_EVENTS = {
	RECEIVE_CHART,
	RECORD_CHART_ERROR,
	REQUEST_CHART,
	UNKNOWN_CHARTS_ACTION
};

export {
	CHARTS_EVENTS
};
