// @flow
const RECEIVE_USERS: 'RECEIVE_USERS' = 'RECEIVE_USERS';
const RECORD_USERS_ERROR: 'RECORD_USERS_ERROR' = 'RECORD_USERS_ERROR';
const REQUEST_USERS: 'REQUEST_USERS' = 'REQUEST_USERS';
const UNKNOWN_USERS_ACTION: 'UNKNOWN_USERS_ACTION' = 'UNKNOWN_USERS_ACTION';

const USERS_EVENTS = {
	RECEIVE_USERS,
	RECORD_USERS_ERROR,
	REQUEST_USERS,
	UNKNOWN_USERS_ACTION
};

export {
	USERS_EVENTS
};
