// @flow
const RECEIVE_CATALOG_ITEM_DATA: 'RECEIVE_CATALOG_ITEM_DATA' = 'RECEIVE_CATALOG_ITEM_DATA';
const RECORD_CATALOG_ITEM_DATA_ERROR: 'RECORD_CATALOG_ITEM_DATA_ERROR' = 'RECORD_CATALOG_ITEM_DATA_ERROR';
const REQUEST_CATALOG_ITEM_DATA: 'REQUEST_CATALOG_ITEM_DATA' = 'REQUEST_CATALOG_ITEM_DATA';
const UNKNOWN_CATALOG_ITEMS_ACTION: 'UNKNOWN_CATALOG_ITEMS_ACTION' = 'UNKNOWN_CATALOG_ITEMS_ACTION';

const CATALOG_ITEMS_EVENTS = {
	RECEIVE_CATALOG_ITEM_DATA,
	RECORD_CATALOG_ITEM_DATA_ERROR,
	REQUEST_CATALOG_ITEM_DATA,
	UNKNOWN_CATALOG_ITEMS_ACTION
};

export {
	CATALOG_ITEMS_EVENTS
};
