// @flow
const RECEIVE_ALL_BUILD_DATA: 'RECEIVE_BUILD_DATAS' = 'RECEIVE_BUILD_DATAS';
const RECEIVE_BUILD_DATA: 'RECEIVE_BUILD_DATA' = 'RECEIVE_BUILD_DATA';
const RECORD_ALL_BUILD_DATA_ERROR: 'RECORD_ALL_BUILD_DATA_ERROR' = 'RECORD_ALL_BUILD_DATA_ERROR';
const RECORD_BUILD_DATA_ERROR: 'RECORD_BUILD_DATA_ERROR' = 'RECORD_BUILD_DATA_ERROR';
const REQUEST_ALL_BUILD_DATA: 'REQUEST_ALL_BUILD_DATA' = 'REQUEST_ALL_BUILD_DATA';
const REQUEST_BUILD_DATA: 'REQUEST_BUILD_DATA' = 'REQUEST_BUILD_DATA';
const UNKNOWN_BUILD_DATA_ACTION: 'UNKNOWN_BUILD_DATA_ACTION' = 'UNKNOWN_BUILD_DATA_ACTION';

const BUILD_DATA_EVENTS = {
	RECEIVE_ALL_BUILD_DATA,
	RECEIVE_BUILD_DATA,
	RECORD_ALL_BUILD_DATA_ERROR,
	RECORD_BUILD_DATA_ERROR,
	REQUEST_ALL_BUILD_DATA,
	REQUEST_BUILD_DATA,
	UNKNOWN_BUILD_DATA_ACTION
};

export {
	BUILD_DATA_EVENTS
};
