// @flow
export const VERIFY_EVENTS = {
	EMPTY_DATA: 'EMPTY_DATA',
	HIDE_LOADER_DATA: 'HIDE_LOADER_DATA',
	SET_ERROR_DATA: 'SET_ERROR_DATA',
	SET_NOTIFICATION_SHOW: 'SET_NOTIFICATION_SHOW',
	SET_UUID_DOCUMENT: 'SET_UUID_DOCUMENT',
	SET_VERIFY_DATA: 'SET_VERIFY_DATA',
	SHOW_LOADER_DATA: 'SHOW_LOADER_DATA'
};
