// @flow
const RECEIVE_ACTUAL_VALUES: 'RECEIVE_ACTUAL_VALUES' = 'RECEIVE_ACTUAL_VALUES';
const RECEIVE_ALL_VALUES: 'RECEIVE_ALL_VALUES' = 'RECEIVE_ALL_VALUES';
const RECEIVE_META_CLASSES: 'RECEIVE_META_CLASSES' = 'RECEIVE_META_CLASSES';
const RECEIVE_STATES: 'RECEIVE_STATES' = 'RECEIVE_STATES';
const RECORD_ACTUAL_VALUES_ERROR: 'RECORD_ACTUAL_VALUES_ERROR' = 'RECORD_ACTUAL_VALUES_ERROR';
const RECORD_ALL_VALUES_ERROR: 'RECORD_ALL_VALUES_ERROR' = 'RECORD_ALL_VALUES_ERROR';
const RECORD_META_CLASSES_ERROR: 'RECORD_META_CLASSES' = 'RECORD_META_CLASSES';
const RECORD_STATES_ERROR: 'RECORD_STATES_ERROR' = 'RECORD_STATES_ERROR';
const REQUEST_ACTUAL_VALUES: 'REQUEST_ACTUAL_VALUES' = 'REQUEST_ACTUAL_VALUES';
const REQUEST_ALL_VALUES: 'REQUEST_ALL_VALUES' = 'REQUEST_ALL_VALUES';
const REQUEST_META_CLASSES: 'REQUEST_META_CLASSES' = 'REQUEST_META_CLASSES';
const REQUEST_STATES: 'REQUEST_STATES' = 'REQUEST_STATES';
const SET_UPLOADED_ACTUAL_VALUES: 'SET_UPLOADED_ACTUAL_VALUES' = 'SET_UPLOADED_ACTUAL_VALUES';
const SET_UPLOADED_ALL_VALUES: 'SET_UPLOADED_ALL_VALUES' = 'SET_UPLOADED_ALL_VALUES';
const UNKNOWN_ATTRIBUTES_DATA_ACTION: 'UNKNOWN_ATTRIBUTES_DATA_ACTION' = 'UNKNOWN_ATTRIBUTES_DATA_ACTION';

const ATTRIBUTES_DATA_EVENTS = {
	RECEIVE_ACTUAL_VALUES,
	RECEIVE_ALL_VALUES,
	RECEIVE_META_CLASSES,
	RECEIVE_STATES,
	RECORD_ACTUAL_VALUES_ERROR,
	RECORD_ALL_VALUES_ERROR,
	RECORD_META_CLASSES_ERROR,
	RECORD_STATES_ERROR,
	REQUEST_ACTUAL_VALUES,
	REQUEST_ALL_VALUES,
	REQUEST_META_CLASSES,
	REQUEST_STATES,
	SET_UPLOADED_ACTUAL_VALUES,
	SET_UPLOADED_ALL_VALUES,
	UNKNOWN_ATTRIBUTES_DATA_ACTION
};

// Лимит значений возвращаемых запросом получения данных атрибута
const LIMIT = 20;

export {
	ATTRIBUTES_DATA_EVENTS,
	LIMIT
};
