// @flow
const RECEIVE_CATALOG_ITEM_SET_DATA: 'RECEIVE_CATALOG_ITEM_SET_DATA' = 'RECEIVE_CATALOG_ITEM_SET_DATA';
const RECORD_CATALOG_ITEM_SET_DATA_ERROR: 'RECORD_CATALOG_ITEM_SET_DATA_ERROR' = 'RECORD_CATALOG_ITEM_SET_DATA_ERROR';
const REQUEST_CATALOG_ITEM_SET_DATA: 'REQUEST_CATALOG_ITEM_SET_DATA' = 'REQUEST_CATALOG_ITEM_SET_DATA';
const UNKNOWN_CATALOG_ITEM_SETS_ACTION: 'UNKNOWN_CATALOG_ITEM_SETS_ACTION' = 'UNKNOWN_CATALOG_ITEM_SETS_ACTION';

const CATALOG_ITEM_SETS_EVENTS = {
	RECEIVE_CATALOG_ITEM_SET_DATA,
	RECORD_CATALOG_ITEM_SET_DATA_ERROR,
	REQUEST_CATALOG_ITEM_SET_DATA,
	UNKNOWN_CATALOG_ITEM_SETS_ACTION
};

export {
	CATALOG_ITEM_SETS_EVENTS
};
