// @flow
const UNKNOWN_SOURCES_FILTERS_ACTION: 'UNKNOWN_SOURCES_FILTERS_ACTION' = 'UNKNOWN_SOURCES_FILTERS_ACTION';
const UPDATE_SOURCE_FILTER: 'UPDATE_SOURCE_FILTER' = 'UPDATE_SOURCE_FILTER';
const UPDATE_SOURCE_FILTERS: 'UPDATE_SOURCE_FILTERS' = 'UPDATE_SOURCE_FILTERS';
const DELETE_SOURCE_FILTER: 'DELETE_SOURCE_FILTER' = 'DELETE_SOURCE_FILTER';
const CLEAR_REQUEST_SOURCE_FILTERS_STATUS: 'CLEAR_REQUEST_SOURCE_FILTERS_STATUS' = 'CLEAR_REQUEST_SOURCE_FILTERS_STATUS';
const REQUEST_SOURCE_FILTERS: 'REQUEST_SOURCE_FILTERS' = 'REQUEST_SOURCE_FILTERS';
const RECEIVE_SOURCE_FILTERS: 'RECEIVE_SOURCE_FILTERS' = 'RECEIVE_SOURCE_FILTERS';
const REQUEST_SOURCE_FILTERS_ERROR: 'REQUEST_SOURCE_FILTERS_ERROR' = 'REQUEST_SOURCE_FILTERS_ERROR';

export const SOURCES_FILTERS_EVENTS = {
	CLEAR_REQUEST_SOURCE_FILTERS_STATUS,
	DELETE_SOURCE_FILTER,
	RECEIVE_SOURCE_FILTERS,
	REQUEST_SOURCE_FILTERS,
	REQUEST_SOURCE_FILTERS_ERROR,
	UNKNOWN_SOURCES_FILTERS_ACTION,
	UPDATE_SOURCE_FILTER,
	UPDATE_SOURCE_FILTERS
};
